name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_bahmni_option:
        description: 'Choose the option to update Bahmni. "Update without removing volumes" or "Update and remove volumes"'
        required: true
        type: choice
        default: update_without_removing_volumes
        options:
          - update_without_removing_volumes
          - update_and_remove_volumes
env:
  UPDATE_BAHMNI_OPTION: ${{ github.event.inputs.update_bahmni_option || 'update_without_removing_volumes'}}

jobs:
  trigger-workflow:
    name: Trigger workflow to deploy to Docker env
    runs-on: ubuntu-latest
    env:
      EVENT_TYPE: openmrs-ipd-openmrs-event
    steps:
      - name: Create repository_dispatch
        run: |
          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${{ secrets.IPD_ORG_NAME }}/${{ secrets.IPD_REPOSITORY_NAME }}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
          if [ $trigger_result == 204 ];then
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
          else
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
            cat trigger_response.txt
            exit 1
          fi
