name: Install Terrascan
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'https://iam.googleapis.com/projects/232842584681/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'ci-user@intrepid-snow-384706.iam.gserviceaccount.com '
