name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_bahmni_option:
        description: 'Choose the option to update Bahmni. "Update without removing volumes" or "Update and remove volumes"'
        required: true
        type: choice
        default: update_without_removing_volumes
        options:
          - update_without_removing_volumes
          - update_and_remove_volumes
env:
  UPDATE_BAHMNI_OPTION: ${{ github.event.inputs.update_bahmni_option || 'update_without_removing_volumes'}}

jobs:
  deploy:
    name: Deploy to QA Instance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'set-command-value'
        name: Set command value based on options chosen
        run: |
          if [ "$UPDATE_BAHMNI_OPTION" == "update_without_removing_volumes" ]; then
            echo "::set-output name=command::without removing volumes"
          elif [ "$UPDATE_BAHMNI_OPTION" == "update_and_remove_volumes" ]; then
            echo "::set-output name=command::with removing volumes && this works"
          fi
      
      - id: 'compute-ssh'
        name: Send commands via SSH
        run: |     
            echo ${{ steps.set-command-value.command }}
            
